version: "3.6"
services:
  grafana:
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.protocol=http"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.rule=Host(`{{ subdomain }}.{{ domain }}`)"
      - "traefik.http.routers.grafana-secure.service=grafana-service"
      - "traefik.http.services.grafana-service.loadbalancer.server.port=3000"
    image: grafana/grafana:latest
    volumes:
      - /opt/docker-data/grafana/data:/var/lib/grafana
      - /opt/docker-data/grafana/etc:/etc/grafana
    environment:
      - PUID={{ user_id }}
      - PGID={{ group_id }}
      - GF_SERVER_ROOT_URL=https://{{ subdomain }}.{{ domain }}:3000/
      - GF_SERVER_DOMAIN={{ subdomain}}.{{ domain }}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_ADMIN_USER={{ username }}
      - GF_SECURITY_ADMIN_PASSWORD={{ password }}
networks:
  proxy:
    external: true

